name: story_app
description: "A project for completion dicoding course intermediate level. https://www.dicoding.com/academies/480."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  http: ^1.2.1
  provider: ^6.0.5
  carousel_slider: ^4.0.0
  lottie: ^2.7.0
  image: ^4.1.3
  permission_handler: ^11.0.1
  go_router: ^13.2.1
  fluttertoast: ^8.2.4
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  timeago: ^3.6.1
  intl: ^0.18.1
  app_settings: ^5.1.1
  flutter_localizations:
    sdk: flutter

  # Media
  camera: ^0.10.5
  camera_windows: ^0.2.1+6
  image_picker: ^1.0.7
  image_picker_windows: ^0.2.1+1

  #Maps and location
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.6+2
  location: ^5.0.3
  geocoding: ^2.2.0

  #Code Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  #Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lotties/
    - assets/fonts/
flutter_intl:
  enabled: true
